eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    service-url:
      defaultZone: http://eureka-0.eureka-service.default.svc.cluster.local:8761/eureka

spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:1234567890Tg!@atlast-cluster.oytbpzt.mongodb.net/orderdb?retryWrites=true&w=majority
